communication:
  url: amqp://localhost

# By providing logging section, you can modify log message location and layout
#
# In this example, these setting are identical to EC default
logging:
  level:
    default: debug
  appenders:
    # To STDOUT
    stdout:
      level: info
      date_pattern: "%H:%M:%S"
      pattern: "%d %5l %c{2}: %m\n"
      # To turn colour on use color_scheme: default
      color_scheme: none
    # To Rolling log file, and log everything
    rolling_file:
      level: all
      log_dir: /var/tmp
      # max 10k of each log file
      size: 10240
      # keep 1 log in total
      keep: 1
      date_pattern: "%F %T %z"
      pattern: "[%d] %-5l %c: %m\n"

# Use OML server located at localhost port 3003
oml_uri: tcp:localhost:3003
