---
# default topic name is this machine's hostname
# default xmpp user name/password is "hostname-pid"
# this is to ensure that every RC has its own topic and XMPP account
:uid: <%= Socket.gethostname %>
:uri: xmpp://<%= "#{Socket.gethostname}-#{Process.pid}" %>:<%= "#{Socket.gethostname}-#{Process.pid}" %>@localhost
:environment: production
:debug: false

:auth:
  :root_cert_dir: /tmp/keys/root
  :entity_cert: /tmp/keys/rc.pem
  :entity_key: /tmp/keys/rc_key.pem
